blank_issues_enabled: true
contact_links:
  - name: PR
    url: https://github.com/libp2p/github-mgmt/edit/master/github/libp2p.yml
    about: Propose GitHub configuration change by modifying libp2p.yml
