blank_issues_enabled: true
contact_links:
  - name: Self-serve Request
    url: https://github.com/libp2p/github-mgmt/edit/master/github/libp2p.yml
    about: Propose a GitHub configuration change by modifying libp2p.yml
